/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-surface-variant": "#4e444b",
        "surface-dim": "#e9d6d7",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#fde9ea",
        "surface-tint": "#7d4f77",
        "on-secondary-container": "#7b5775",
        "on-background": "#23191a",
        "primary-fixed": "#ffd7f5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#eddfdf",
        "primary-fixed-dim": "#eeb5e3",
        "outline-variant": "#d1c2cb",
        "on-secondary-fixed": "#2d112b",
        "inverse-primary": "#eeb5e3",
        "on-tertiary-container": "#aa9e9e",
        tertiary: "#282121",
        "tertiary-fixed-dim": "#d0c4c3",
        "on-surface": "#23191a",
        secondary: "#765371",
        "tertiary-container": "#3e3636",
        "secondary-fixed-dim": "#e5b9dc",
        "primary-container": "#52284e",
        "on-tertiary-fixed": "#211a1a",
        surface: "#fff8f7",
        primary: "#3a1237",
        "on-primary-fixed": "#320b30",
        "on-primary-fixed-variant": "#63375e",
        outline: "#80747c",
        "on-tertiary-fixed-variant": "#4d4545",
        background: "#fff8f7",
        "on-secondary-fixed-variant": "#5d3c58",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-variant": "#f1dedf",
        "surface-container-low": "#fff0f1",
        "inverse-surface": "#392e2f",
        "secondary-fixed": "#ffd7f6",
        "surface-container-high": "#f7e4e5",
        "inverse-on-surface": "#ffeced",
        "on-primary-container": "#c690bc",
        "secondary-container": "#ffd2f5",
        "surface-bright": "#fff8f7",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#f1dedf",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Cormorant Garamond", "serif"],
        body: ["Cormorant Garamond", "serif"],
        label: ["Cormorant Garamond", "serif"],
      },
    },
  },
  plugins: [],
}
